### ISSUE TITLE
Can't Send Messages / Frequent Crashes

### ISSUE THREAD

**Issue by lucky4281** [Cellomonster/iOS-Raspberry#1]
iPhone 4s iOS 6.1.3

The app works great. Servers load and chats occasionally load. The app crashes sometimes when choosing multiple text channels quickly, and the keyboard doesn't go away after typing. Send button and camera buttons don't work as well. Users menu is blank, too.

Anyways, this is a super cool and interesting project! Keep it up.

**Comment by cellomonster** [comment]
sending messages isn't supported yet (this is still an early work in progress)

I did find the cause of the channel-switching crash. It occurs if you switch channels while image messages are still loading. Will fix that up, thanks!
