### ISSUE TITLE
Not building on Xcode version 11.5

### ISSUE THREAD

**Issue by SparkyPotato** [Cellomonster/iOS-Raspberry#5]
When trying to build for iOS 6.1.6, the storyboard files aren't supported.
How would you recommend I build for an iPod Touch 4?

**Comment by cellomonster** [comment]
I do not know how you would configure xcode 11 to build applications for ios 6 (or of it's even possible). I'm using xcode 5 on OS X 10.9 with an iOS 6 sdk pulled from xcode 4

**Comment by SparkyPotato** [comment]
Oh, that makes sense. Apple ended support for iOS 6 in 7.3, and that version of Xcode doesn't run on Catalina.
